/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.DesenhaObjetos;
import java.awt.Graphics2D;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Poligono;
import model.Ponto;
import static view.NMain.painelPintura;

/**
 *
 * @author renan
 */
public class Poligonowind extends javax.swing.JFrame {

    /**
     * Creates new form Squarewind
     */
    public Poligonowind() {
        initComponents();
    }
    Poligono poligono = new Poligono();

    private int contavetor = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        linha_innerpanel = new javax.swing.JPanel();
        bAddVetorPoligono = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        y1Poligono = new javax.swing.JTextField();
        x1Poligono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bAddPoligono = new javax.swing.JButton();
        bRmvVetorPoligono = new javax.swing.JButton();
        bCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vetorListpoligono = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 400));
        setMaximizedBounds(new java.awt.Rectangle(516, 239, 239, 239));
        setMinimumSize(new java.awt.Dimension(516, 239));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        linha_innerpanel.setBackground(new java.awt.Color(255, 255, 255));
        linha_innerpanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(0, 0, 0)), "Adicionar Poligono", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        bAddVetorPoligono.setBackground(new java.awt.Color(255, 255, 255));
        bAddVetorPoligono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bAddVetorPoligono.setText(">>");
        bAddVetorPoligono.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bAddVetorPoligono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddVetorPoligonoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Vetor");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Eixo X:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Eixo Y:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Lista de Vetores");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bAddPoligono.setBackground(new java.awt.Color(255, 255, 255));
        bAddPoligono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bAddPoligono.setText("Adicionar");
        bAddPoligono.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bAddPoligono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddPoligonoActionPerformed(evt);
            }
        });

        bRmvVetorPoligono.setBackground(new java.awt.Color(255, 255, 255));
        bRmvVetorPoligono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bRmvVetorPoligono.setText("XX");
        bRmvVetorPoligono.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bRmvVetorPoligono.setEnabled(false);

        bCancelar.setBackground(new java.awt.Color(255, 255, 255));
        bCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bCancelar.setText("Cancelar");
        bCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarActionPerformed(evt);
            }
        });

        vetorListpoligono.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PONTO", "VALOR X", "VALOR Y"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        vetorListpoligono.setEnabled(false);
        vetorListpoligono.setGridColor(new java.awt.Color(255, 255, 255));
        vetorListpoligono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vetorListpoligonoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(vetorListpoligono);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Nome:");

        javax.swing.GroupLayout linha_innerpanelLayout = new javax.swing.GroupLayout(linha_innerpanel);
        linha_innerpanel.setLayout(linha_innerpanelLayout);
        linha_innerpanelLayout.setHorizontalGroup(
            linha_innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(linha_innerpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(linha_innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, linha_innerpanelLayout.createSequentialGroup()
                        .addGroup(linha_innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(linha_innerpanelLayout.createSequentialGroup()
                                .addGroup(linha_innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(linha_innerpanelLayout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(x1Poligono, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(linha_innerpanelLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(y1Poligono, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(linha_innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bAddVetorPoligono)
                                    .addComponent(bRmvVetorPoligono, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(linha_innerpanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, linha_innerpanelLayout.createSequentialGroup()
                        .addGap(0, 216, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, linha_innerpanelLayout.createSequentialGroup()
                        .addComponent(bCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bAddPoligono)))
                .addContainerGap())
        );
        linha_innerpanelLayout.setVerticalGroup(
            linha_innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, linha_innerpanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(linha_innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(linha_innerpanelLayout.createSequentialGroup()
                        .addGroup(linha_innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(linha_innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(x1Poligono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bRmvVetorPoligono))
                        .addGap(18, 18, 18)
                        .addGroup(linha_innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(y1Poligono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bAddVetorPoligono))))
                .addGap(18, 18, 18)
                .addGroup(linha_innerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAddPoligono)
                    .addComponent(bCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(linha_innerpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 256, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(linha_innerpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_bCancelarActionPerformed

    private void bAddPoligonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddPoligonoActionPerformed
        if (vetorListpoligono.getModel().getRowCount() >= 3) {
            Ponto p = new Ponto(poligono.getPontosPoligono().get(0).getX(), poligono.getPontosPoligono().get(0).getY());
            poligono.getPontosPoligono().add(p);
            poligono.setNome(nome.getText());
            DesenhaObjetos.poligonos.add(poligono);
            DesenhaObjetos.desenhaObjetos((Graphics2D) painelPintura.getGraphics());
            poligono = new Poligono();
            dispose();
        } else {
            JOptionPane.showConfirmDialog(null, "Adicione Vetores!", "", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_bAddPoligonoActionPerformed

    private void bAddVetorPoligonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddVetorPoligonoActionPerformed
        DefaultTableModel model = (DefaultTableModel) vetorListpoligono.getModel();
        if (!x1Poligono.getText().equals("") && !y1Poligono.getText().equals("")) {
            Ponto p = new Ponto(Integer.parseInt(x1Poligono.getText()), Integer.parseInt(y1Poligono.getText()));
            poligono.getPontosPoligono().add(p);
            model.addRow(new Object[]{"Posicao " + contavetor, p.getX(), p.getY()});
            contavetor++;
            System.out.println("Adicinou Vetor!");
            x1Poligono.setText("");
            y1Poligono.setText("");
        } else {
            JOptionPane.showConfirmDialog(null, "Favor preencher os vetores!", "", JOptionPane.PLAIN_MESSAGE);
            // TODO add your handling code here:
        }         // TODO add your handling code here:
    }//GEN-LAST:event_bAddVetorPoligonoActionPerformed

    private void vetorListpoligonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vetorListpoligonoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_vetorListpoligonoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Poligonowind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Poligonowind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Poligonowind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Poligonowind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Poligonowind().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddPoligono;
    private javax.swing.JButton bAddVetorPoligono;
    private javax.swing.JButton bCancelar;
    private javax.swing.JButton bRmvVetorPoligono;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel linha_innerpanel;
    private javax.swing.JTextField nome;
    public static javax.swing.JTable vetorListpoligono;
    private javax.swing.JTextField x1Poligono;
    private javax.swing.JTextField y1Poligono;
    // End of variables declaration//GEN-END:variables
}
